### ISSUE TITLE
Moodle 3.9 compatibility

### ISSUE THREAD

**Issue by debuglevel** [jonof/moodle-antivirus_savdi#10]
On [https://moodle.org/plugins/antivirus_savdi] the plugin is not yet listed as 3.9 compatible. I guess no serious changes (if any at all) have to be made for 3.9 compatibility, though I did not yet check if it works.

**Comment by jonof** [comment]
The published release is compatible, however if anyone wishes to try what is waiting in the 'testclient' branch on 3.9 and report back, that would be appreciated. My employer is about to start our 3.9 upgrade cycle, so I have been waiting to get some real first-hand testing in before I declare the changes complete and publish an officially 3.9-safe version.

**Comment by jonof** [comment]
A new version declaring 3.9 support is now published.
