### ISSUE TITLE
Scanner error on remote daemon

### ISSUE THREAD

**Issue by Peterburnett** [jonof/moodle-antivirus_savdi#11]
We have been encountering a lot of scanner errors due to `Data sent was shorter than expected`. These seem to primarily occur with large video files from 100Mb to 1.4Gb. I haven't done a deep dive on it, but my best guess its just failing due to network flakiness occasionally. I propose we just have a configurable retry option similar to ClamAV, that will allow for these to be rerun before failing. While this might be a lot of extra time during the upload process for a user, it should generally be lower than the time taken to actually do the file upload in the first place.

I won't have capacity to fix this for the next few weeks, but I may be able to PR this in the next few months.

**Comment by jonof** [comment]
It's also possible that I need to have `client::senddata()` and `client::senddatastream()` make an effort to send all the bytes using multiple calls to `fwrite()`/`stream_copy_to_stream()` if they don't succeed in completing it on the first call. When I'm back on the university LAN next week I'll see if I can reproduce it.

**Comment by Peterburnett** [comment]
For us it has been videos pretty consistently, if you can get a 1gb file or so, and just upload it a few times, you may run into the issue. We are currently receiving 1-3 emails about this a day, and its blocking us from turning on error treat as virus, as we don't want to block these from being uploaded.

**Comment by jonof** [comment]
Our network must be too reliable because I can't cause it to foul up. I have started work in the "senddata-in-pieces" branch to make writes to the daemon be continued if they return a short count of data sent. That obviously won't help if the connection is indeed being dropped, so retrying will be added next.

**Comment by Peterburnett** [comment]
Hi @jonof, has there been any movement on this branch? I may be able to do whatever is required to get it over the line, if you do not have the time.
Thanks!

**Comment by jonof** [comment]
Not since what I posted on 4 August. I'm interested to know if the change I've made has any effect in your environment.

**Comment by Peterburnett** [comment]
I will do some live testing on the new branch then, and see how it plays. Thanks for your help on this so far!

**Comment by Peterburnett** [comment]
Hi Jon,

I have dumped 5gbs of data through 2 parallel environments, and have been unable to reproduce the issue, with and without the patch, whereas we were seeing this issue much more consistently ~2 months ago. This may be due to some underlying stability improvements in AWS land, or something else, but the patch definitely didnt _hurt_ anything in our setup. I will leave this deployed to these environments for a few weeks for further testing, but I suspect this patch is good to go.

Thanks

**Comment by jonof** [comment]
Thanks. I've found one misbehaviour if the connection to the server is lost during a `client::scandata()` call, which I will need to solve otherwise it gets stuck in an endless loop.
