### ISSUE TITLE
Indicate noteworthy SCANDATA vs SCANFILE result

### ISSUE THREAD

**Issue by debuglevel** [jonof/moodle-antivirus_savdi#12]
I really like the test client to check if everything is working. But I have `antivirus_savdi | scannerisremote` enabled and wondered what is wrong here:
![image](https://user-images.githubusercontent.com/2401265/90310934-68375800-def6-11ea-9bfc-f3445e9a51a1.png)
At least until I noticed that for `scannerisremote` only the SCANDATA result is noteworthy.

Probably I should just disable the SCANFILE feature on SAVDID. But I didn't and I was very confused :-). So it might be helpful to indicate which of SCANDATA/SCANFILE is actually the interesting one (depending on `scannerisremote`).

**Comment by brendanheywood** [comment]
We've just hit this one too
