### ISSUE TITLE
Remote access does not use Moodle's proxy settings

### ISSUE THREAD

**Issue by danmarsden** [jonof/moodle-antivirus_savdi#4]
As you are using stream_socket_client directly you should probably check Moodle's web proxy settings ($CFG->proxyhost, $CFG->proxyuser etc) and use them when the rquest is going out externally.

I don't think this is a blocker for approval in the plugins db at this stage because the plugin is usable on localhost without the proxy settings.

**Comment by jonof** [comment]
Firstly, the protocol isn't HTTP. Secondly, I'd be very curious to know why someone would deploy a SAV-DI daemon on their network in such a manner that they can only talk to it via a HTTP CONNECT tunnel or SOCKS proxy. They wouldn't tunnel/proxy their database connections that way, so why the virus scanner?

**Comment by danmarsden** [comment]
I'm guessing you didn't see my comments in https://tracker.moodle.org/browse/CONTRIB-8017 ? :-)

**Comment by jonof** [comment]
I did not, sorry. Tracker notifications to my work mailbox and Github's go to my private address. I'll make mention of ensuring a clear path through firewalls for remote daemons.
