### ISSUE TITLE
Implement a status check

### ISSUE THREAD

**Issue by brendanheywood** [jonof/moodle-antivirus_savdi#5]
https://docs.moodle.org/dev/Check_API

ie do a raw-ish direct data only eicar submission, and make sure it connects, and detects the failure, and does so in some reasonable time limit (maybe < 1 sec for a pure data check)

This doesn't need to be run on every check, it could be cached for say 1 hour

**Comment by jonof** [comment]
Noted. I'll explore it soon when I start work on our 3.9 cycle. One initial thought: how likely is it that paranoid admins will look in their savdi log, see repeated EICAR hits, and protest that the plugin is regularly throwing up positive results?

**Comment by debuglevel** [comment]
Maybe add an option to disable this for paranoid admins.

Furthermore it would be nice if the testclient also does this check.
