### ISSUE TITLE
Scanning on local filesystem should probably not encode path

### ISSUE THREAD

**Issue by debuglevel** [jonof/moodle-antivirus_savdi#9]
In `scanlocal()`, client.php URL-encodes the file path.

https://github.com/jonof/moodle-antivirus_savdi/blob/028120c9a6013fe01fb4b742ee31a72417284d7e/classes/client.php#L302

Is this intended?

**Comment by jonof** [comment]
The spec says it's not necessary unless `\r` or `\n` are in the file path, however I have verified the behaviour of "SAV Dynamic Interface 2.2.0" when the whole path is encoded, and on that version at least it's happy to accept it.
```
> OK SSSP/1.0
< SSSP/1.0
> ACC 5EE1AE85/1
< SCANFILE %2Fvar%2Fopt%2Frh%2Frh-php71%2Ftmp%2Ftest%20%25%0D%0Afile
> ACC 5EE1AE85/2
> VIRUS EICAR-AV-Test /var/opt/rh/rh-php71/tmp/test%20%25%0D%0Afile
/var/opt/rh/rh-php71/tmp/test%20%25%0D%0Afile: EICAR-AV-Test FOUND
> OK 0203 /var/opt/rh/rh-php71/tmp/test%20%25%0D%0Afile
> DONE OK 0203 Virus found during virus scan
> 
< BYE
> BYE
```
What path is failing for you with what SAVDI version?

**Comment by debuglevel** [comment]
Okay, I should have looked up the specs first. An URL encoded local path just seemed like a too obvious reason for my scanning problem. It then seems to be related with some other issue.
Nevermind. :)

**Comment by jonof** [comment]
No problem. Local file scanning has extra hurdles, especially if you're on a distribution with private /tmp enabled for PHP/Apache, like RHEL7+. There will be improvements to try and identify certain issues with configuration.

**Comment by debuglevel** [comment]
As the server runs CentOS 7, this seems to be the actual problem. Thanks for pointing in the right direction!
